apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-api-config
  labels:
    app: employee-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
