apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
  labels:
    app: employee-api
spec:
  type: LoadBalancer
  selector:
    app: employee-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  sessionAffinity: None
